name: Solar system workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main:
      - 'feature/*':

jobs:
  unit-testing:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup nodejs version
    - uses: actions/setup-node@v4
        with:
          node-version: 18

    - name: Install npm
      run: npm install

    - name: Unit Testing
      run: npm test
      
